# <center> Introduction to Python </center>
## <center> [For more information, check the link here.](https://www.py4e.com/lessons) </center>




## Agenda 

- Constants and Variables
- Types of variables
- Conditional statement
- Debugging codes
- Data collection and presentation

[For online lab click here](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo/Lorenz.ipynb)


## 1- Constants:

Fixed values that can not be changed such as numbers or letters.

#### example: 

print(54) <br>
print('Hello Class!') <br>





In [1]:
print(54) 
print('Hello Class!') 

54
Hello Class!


## 2- Variables:

Named places in the memory where a programmer can store data and later retrieve them (with the variable name).

#### example: 

A= 14 <br>
B= 29 <br>
A= 32 <br>
<br>
A=?

In [3]:
A= 14 
B= 29 
A= 32 

A

32

## 3- Numerical Expressions

* Addition     +
* Subtraction  -
* Multiplication *
* Division /
* Power **
* Remainder %

In [1]:
23 % 7

2

## 4- Types of Variables and Constants

* int
* str
* float

### example:

* type('Hamilton')=?
* type(53)=?
* type(53.2)=?


In [9]:
type(53)

int

## 5- Conditional Execution

* Less than <
* Less than or equal to <=
* Greater than >
* Greater than or equal to >=
* Equal to ==
* Not Equal to !=


In [21]:
x=35

if x == 35:
    print('It was equal ...')

if x < 100:
        print('It was less than ...')
    
    

It was equal ...
It was less than ...


In [23]:
x=35

if x == 35:
    print('It was equal ...')

elif x < 100:
        print('It was less than ...')
    
    

It was equal ...


In [25]:
y= 'Canada'

if y== 'USA':
    print(Y)
    
else:
    print('They were not equal ...')

They were not equal ...


## 6- Debugging codes with "Try/Except"

* If the code in "try" works, the "except" section is skipped.
* If the code in the try fails, it jumps to the "except" section.

In [9]:
Book = 'Hello Bob'
Pen = int(Book)
print('First', Book)




ValueError: invalid literal for int() with base 10: 'Hello Bob'

In [6]:
try:
    Book = 'Hello Bob'
    Pen = int(hello)
    print('First', Book)
    
except:
    print('Program continued but you should check the first part ...')
    
    
    

Program continued but you should check the first part ...


## Lists [[Ref]](https://www.py4e.com/lessons/lists)

* List constants are separated by commas and surrounded by square brackets.
* List can have any python object even another list
* List are mutable 


In [116]:
A=[2,3,[4,5],9]

type(A)

list

In [117]:
A[2]   #List can have any python object even another list

[4, 5]

In [118]:
A[2]='Book'     #List are mutable
A

[2, 3, 'Book', 9]

In [21]:
B='Pen'

In [19]:
B[1]='C'  #Strings are not mutable

NameError: name 'B' is not defined

#### Question: What will be the output of List1 + List2

## Tuples [[Ref]](https://www.py4e.com/lessons/tuples)

Tuples are not mutable (similar to strings but unlike to lists).

In [2]:
B=(2,3,[4,5],9)

In [3]:
B[2]

[4, 5]

In [4]:
B[2]='Book'

TypeError: 'tuple' object does not support item assignment

## Dictionaries [[Ref]](https://www.py4e.com/lessons/dictionary)

- Powerful data collection in Python
- Dictionaries can do fast database-like operations in Python

In [23]:
Uni={'Book':36, 'Pen':64 , 'Name': ['Dave',56,(39,87,5)] , 3:'winner'
}

Uni

{'Book': 36, 'Pen': 64, 'Name': ['Dave', 56, (39, 87, 5)], 3: 'winner'}

In [24]:
Uni['Name']

['Dave', 56, (39, 87, 5)]

In [15]:
Uni[3]

'halk'

In [16]:
type(Uni)

dict

## Commonly used libraries in Python:

![PYlib](Figs/libraries.PNG)

## Data presentation in Numpy [[Ref]](https://docs.scipy.org/doc/numpy/user/quickstart.html)
* np.array
* ndarray.shape
* ndarray.dtype

In [44]:
import numpy as np
k=[[2,3,9],[3,1,6]]
b=np.array(k)
b

array([[2, 3, 9],
       [3, 1, 6]])

In [45]:
b.shape

(2, 3)

In [32]:
b[0,:]

array([2, 3, 9])

In [47]:
B=np.arange(36)
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [48]:
C=B.reshape(2,3,2,3)
C

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]]])

In [49]:
C.shape

(2, 3, 2, 3)

#### Dimensions in numpy arrays:
<center> <img src="Figs/Dim.PNG" height="200" width="400"> </center>

In [51]:
C[:,:,1,0]

array([[ 3,  9, 15],
       [21, 27, 33]])

## Data presentation in Pandas [[Ref]](https://pandas.pydata.org/pandas-docs/stable/10min.html)
* pd.Series()
* pd.DataFrame()
* df.head()
* df.describe()
* df.info()
* df.dtypes
* df.shape
* df.columns
* df.values
* df.T

In [3]:
import pandas as pd
import numpy as np

#### Creating a Series by passing a list of values:

In [61]:
k = pd.Series([8,5,np.nan,10,2])

k

0     8.0
1     5.0
2     NaN
3    10.0
4     2.0
dtype: float64

In [62]:
type(k)

pandas.core.series.Series

#### Creating DataFrame from dictionary 

In [71]:
df = pd.DataFrame({'A' : 1.,
                    'C' : pd.Series(list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo' })
df

A    C  D      E    F
0  1.0  0.0  3   test  foo
1  1.0  1.0  3  train  foo
2  1.0  2.0  3   test  foo
3  1.0  3.0  3  train  foo

#### Visualizing DataFrame

In [72]:
df.head()

A    C  D      E    F
0  1.0  0.0  3   test  foo
1  1.0  1.0  3  train  foo
2  1.0  2.0  3   test  foo
3  1.0  3.0  3  train  foo

In [73]:
df.describe()

A         C    D
count  4.0  4.000000  4.0
mean   1.0  1.500000  3.0
std    0.0  1.290994  0.0
min    1.0  0.000000  3.0
25%    1.0  0.750000  3.0
50%    1.0  1.500000  3.0
75%    1.0  2.250000  3.0
max    1.0  3.000000  3.0

In [78]:
df.info()  # Basic information about the datframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
A    4 non-null float64
C    4 non-null float32
D    4 non-null int32
E    4 non-null category
F    4 non-null object
dtypes: category(1), float32(1), float64(1), int32(1), object(1)
memory usage: 276.0+ bytes


In [76]:
df.dtypes

A     float64
C     float32
D       int32
E    category
F      object
dtype: object

In [79]:
df.shape

(4, 5)

In [91]:
df.columns

Index(['A', 'C', 'D', 'E', 'F'], dtype='object')

In [80]:
df.T

0      1     2      3
A     1      1     1      1
C     0      1     2      3
D     3      3     3      3
E  test  train  test  train
F   foo    foo   foo    foo

#### Converting dataframe to numpy array

In [93]:
A=df.values

A

array([[1.0, 0.0, 3, 'test', 'foo'],
       [1.0, 1.0, 3, 'train', 'foo'],
       [1.0, 2.0, 3, 'test', 'foo'],
       [1.0, 3.0, 3, 'train', 'foo']], dtype=object)

In [85]:
type(A)

numpy.ndarray

#### Question: What is the type of "one column" in a dataframe?

In [40]:
type(df['A'])

pandas.core.series.Series